### ISSUE TITLE
Looking forward to adding new tree component

### ISSUE THREAD

**Issue by 2775668948** [fay-org/fect#132]
# Feature request 🚀

### Expected:

 Add Tree component

### Others:
1.0.3版本已经发布快一个月了,是否有计划在发布1.0.4版本之前添加树形组件呢?期待树形组件的加入。

**Comment by XeryYue** [comment]
@2775668948 有计划考虑但是我一个人有点忙下个版本会在月底发布计划是加入表单。整个组件库的风格向pc 方向靠拢
