### ISSUE TITLE
select组件下拉框只能向下展开

### ISSUE THREAD

**Issue by QiYuOr2** [fay-org/fect#135]
# Bug report 🐞

## Version & Environment

- `@fect-ui/vue 1.0.5-rc.0`
- `vue 3.0.0`

## Expection

下拉框靠近屏幕底部希望可以向上展开

## Actual results (or Errors)

向下展开，并且增加了页面的高度
![image](https://user-images.githubusercontent.com/48339849/140869662-d6b907c3-69ca-4d1f-b777-55b711c78649.png)

**Comment by XeryYue** [comment]
@QiYuOr2  Thanks for you attention .  It doesn't look as expected . Is my mistake . i will fix them in next `rc` version .

**Comment by XeryYue** [comment]
@QiYuOr2  We fix it . and it will works in next `rc` version
