### ISSUE TITLE
The new website document language switch did not work

### ISSUE THREAD

**Issue by 2775668948** [fay-org/fect#146]
# Bug report 🐞
The new website document language switch did not work.I tried to clear the website cache and switch browsers, but the problem still exists.
## Version & Environment
The website document is now in English by default. I tried to click to switch the language. The route was changed, but the language was not switched.
## Expection
Language can be switched normally
## Actual results (or Errors)
![image](https://user-images.githubusercontent.com/58553792/145028555-bdbd2a11-ef12-45e5-b2d5-e4e962eee198.png)
![Uploading image.png…]()

**Comment by 2775668948** [comment]
Sorry, I seem to be mistaken. It turned out that the new domain name file supports switching between Chinese and English. It is normal now. Now I will bookmark the new document address.

**Comment by XeryYue** [comment]
@2775668948  : ) .  Thanks for you attention,  Now, home page is only with English . I am busy now so i can't set Chinese version . But It will be a good suggestion in feature , And in tips  is that `vue-rc` domain  only work for canary version .
